from PyQt5 import QtCore, QtGui, QtWidgets
import paths


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        super().__init__()
        MainWindow.resize(442, 463)
        MainWindow.setMinimumSize(QtCore.QSize(442, 463))
        MainWindow.setMaximumSize(QtCore.QSize(442, 463))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(paths.icon_path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.label_fondo = QtWidgets.QLabel(self.centralwidget)
        self.label_fondo.setGeometry(QtCore.QRect(-10, -10, 521, 491))
        self.label_fondo.setText("")
        self.label_fondo.setPixmap(QtGui.QPixmap(paths.fondo_path))
        self.label_fondo.setScaledContents(True)
        self.labelTitulo = QtWidgets.QLabel(self.centralwidget)
        self.labelTitulo.setGeometry(QtCore.QRect(130, 90, 181, 71))
        self.labelTitulo.setScaledContents(True)
        self.labelAutor = QtWidgets.QLabel(self.centralwidget)
        self.labelAutor.setGeometry(QtCore.QRect(190, 140, 61, 16))
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(110, 260, 211, 31))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_nick = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.horizontalLayout.addWidget(self.label_nick)
        self.line_nick = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.line_nick.setMaxLength(12)
        self.horizontalLayout.addWidget(self.line_nick)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(110, 210, 211, 31))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_ip = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.addWidget(self.label_ip)
        spacerItem = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.line_ip = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.addWidget(self.line_ip)
        self.boton_conectar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_conectar.setGeometry(QtCore.QRect(160, 320, 111, 31))
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 420, 421, 30))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_emergencia = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_emergencia.setText("")
        self.horizontalLayout_3.addWidget(self.label_emergencia)
        self.line_mensaje = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.addWidget(self.line_mensaje)
        self.boton_enviar = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.addWidget(self.boton_enviar)
        self.label_gris_qrect = QtCore.QRect(-10, 410, 471, 91)
        self.label_gris = QtWidgets.QLabel(self.centralwidget)
        self.label_gris.setGeometry(self.label_gris_qrect)
        self.label_gris.setText("")
        self.label_gris.setPixmap(QtGui.QPixmap(paths.label_gris_path))
        self.label_fondo.raise_()
        self.label_gris.raise_()
        self.labelTitulo.raise_()
        self.labelAutor.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.boton_conectar.raise_()
        self.horizontalLayoutWidget_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 442, 21))
        MainWindow.setMenuBar(self.menubar)
        '''
        ELEMENTOS QUE APARECEN EN 2da INSTANCIA LOS ESCONDEMOS
        '''
        self.boton_enviar.hide()
        self.line_mensaje.hide()
        self.label_gris.hide()
        '''
        -----------------------------------------
        '''
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chat Cifrado"))
        self.labelTitulo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#ffffff;\">CHAT CIFRADO</span></p></body></html>"))
        self.labelTitulo.resize(self.labelTitulo.sizeHint())
        self.labelAutor.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#5b5b5b;\">Heinz Busch</span></p></body></html>"))
        self.labelAutor.resize(self.labelAutor.sizeHint())
        self.label_nick.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#ffffff;\">NICKNAME:</span></p></body></html>"))
        self.label_nick.resize(self.label_nick.sizeHint())
        self.label_ip.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#ffffff;\">IP:</span></p></body></html>"))
        self.label_ip.resize(self.label_ip.sizeHint())
        self.boton_conectar.setText(_translate("MainWindow", "CONECTAR"))
        self.boton_enviar.setText(_translate("MainWindow", "Enviar"))
